### ISSUE TITLE
Archive created using fixed size and no compression cannot be cloned

### ISSUE THREAD

**Issue by rminderhoud** [oll3/bita#18]
I was able to create an archive that I cannot clone on bita 0.9.0. Steps:

- `bita compress --fixed-size 64 --compression none -i agreement.hlp agreement.cba`
- `bita clone agreement.cba agreement_new.hlp`

I started with no compression and a fix sized chunking strategy to try to keep it simple but based on some of the code I suspect there's a different set of configurations that are better supported than fix sized/no compression. I intend to look further into this but wanted to get the issue up

[agreement.zip](https://github.com/oll3/bita/files/7836576/agreement.zip)

**Comment by oll3** [comment]
Interesting. And not too surprised when both the fixed size chunking and not compressing hasn't seen much use, at least not on my side. But thanks for reporting, will definitely have a look at it.

**Comment by rminderhoud** [comment]
> Interesting. And not too surprised when both the fixed size chunking and not compressing hasn't seen much use, at least not on my side. But thanks for reporting, will definitely have a look at it.

Turns out it had nothing to do with the configuration but was a big in `bita` on windows!
