### ISSUE TITLE
Provide binary releases

### ISSUE THREAD

**Issue by MCOfficer** [oll3/bita#24]
I want to move the bita generation job from my jenkins to an ephemeral environment, namely github actions. To this end, it would be very convenient to have binaries I can download, instead of compiling bita from scratch on every run.

**Comment by oll3** [comment]
> I want to move the bita generation job from my jenkins to an ephemeral environment, namely github actions. To this end, it would be very convenient to have binaries I can download, instead of compiling bita from scratch on every run.

Seems like a good idea. And probably not to hard using GH actions and artifacts. A PR would be welcome! ⭐

**Comment by MCOfficer** [comment]
> > I want to move the bita generation job from my jenkins to an ephemeral environment, namely github actions. To this end, it would be very convenient to have binaries I can download, instead of compiling bita from scratch on every run.
> 
> Seems like a good idea. And probably not to hard using GH actions and artifacts. A PR would be welcome! ⭐

I take it it's pretty much just `cargo build --release`, no further oddities?

**Comment by oll3** [comment]
I presume you want Linux x86_64 binaries, no? :)
But yes, I think that would be sufficient as a first step. Possibly linking statically with musl to be less dependent on a specific libc version, but is not necessary. If anyone wants to add windows binaries or a binaries with different features enabled (lzma/zstd/rustls) I think it can be added in time.

**Comment by MCOfficer** [comment]
I know not much has happened since 0.10.0, but would you mind pushing a new release? I imagine this should also me #28 happy.

**Comment by oll3** [comment]
Been meaning to do it for some time... Now it's published anyway, with the macOS fix.
