### ISSUE TITLE
update failed in bita

### ISSUE THREAD

**Issue by hhhyyy123wg** [oll3/bita#40]
thread '<unnamed>' panicked at /home/lynxi/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/bitar-0.11.0/src/archive.rs:286:46:
index out of bounds: the len is 5898 but the index is 5898
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 3493789840

**Comment by hhhyyy123wg** [comment]
When transferring the bita compressed file across different systems (Windows & Linux) through drag-and-drop, data alterations may occur, leading to errors. Is it possible to implement some error handling?

**Comment by oll3** [comment]
> When transferring the bita compressed file across different systems (Windows & Linux) through drag-and-drop, data alterations may occur, leading to errors. Is it possible to implement some error handling?

Hi @hhhyyy123wg ,

Seems like a strange file transfer tool that would do this to a file. But I agree that it would be nice with a more descriptive error when an archive is corrupted this way. I haven't looked into the details but I would've thought that the archive header and number of chunks should have already been validated by checksum at this point in the process, so a bit strange that this is occuring.

Would it be possible to provide one of your faulty archives, preferably with a valid copy of it too, and I might be able to investigate it further?
